// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package state

type LabelInventory struct {
	Name      string
	FirstSeen string
	UseCount  int64
}

type ProcessedBookmark struct {
	BookmarkID    string
	ClassifiedAt  string
	AppliedLabels string
	LlmModel      string
	Confidence    float64
}
