// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package state

import (
	"context"
)

const getProcessedDetail = `-- name: GetProcessedDetail :one
SELECT
    bookmark_id,
    classified_at,
    applied_labels,
    llm_model,
    confidence
FROM processed_bookmarks
WHERE bookmark_id = ?
`

func (q *Queries) GetProcessedDetail(ctx context.Context, db DBTX, bookmarkID string) (ProcessedBookmark, error) {
	row := db.QueryRowContext(ctx, getProcessedDetail, bookmarkID)
	var i ProcessedBookmark
	err := row.Scan(
		&i.BookmarkID,
		&i.ClassifiedAt,
		&i.AppliedLabels,
		&i.LlmModel,
		&i.Confidence,
	)
	return i, err
}

const isProcessed = `-- name: IsProcessed :one

SELECT EXISTS (
    SELECT 1
    FROM processed_bookmarks
    WHERE bookmark_id = ?
) AS processed
`

// SPDX-License-Identifier: GPL-3.0-or-later
//
// sqlc queries for the readeckorator state store.
//
// These are the only schema-touching statements in the application;
// everything else is hand-written Go on top of the generated query
// methods. When you change the schema, also update queries.sql and
// run `make sqlc`.
func (q *Queries) IsProcessed(ctx context.Context, db DBTX, bookmarkID string) (int64, error) {
	row := db.QueryRowContext(ctx, isProcessed, bookmarkID)
	var processed int64
	err := row.Scan(&processed)
	return processed, err
}

const listLabels = `-- name: ListLabels :many
SELECT name, first_seen, use_count
FROM label_inventory
ORDER BY use_count DESC, name ASC
`

func (q *Queries) ListLabels(ctx context.Context, db DBTX) ([]LabelInventory, error) {
	rows, err := db.QueryContext(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabelInventory{}
	for rows.Next() {
		var i LabelInventory
		if err := rows.Scan(&i.Name, &i.FirstSeen, &i.UseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLabel = `-- name: UpsertLabel :exec
INSERT INTO label_inventory (name, first_seen, use_count)
VALUES (?, ?, 1)
ON CONFLICT (name) DO UPDATE SET
    use_count = use_count + 1
`

type UpsertLabelParams struct {
	Name      string
	FirstSeen string
}

func (q *Queries) UpsertLabel(ctx context.Context, db DBTX, arg UpsertLabelParams) error {
	_, err := db.ExecContext(ctx, upsertLabel, arg.Name, arg.FirstSeen)
	return err
}

const upsertProcessed = `-- name: UpsertProcessed :exec
INSERT INTO processed_bookmarks
    (bookmark_id, classified_at, applied_labels, llm_model, confidence)
VALUES
    (?, ?, ?, ?, ?)
ON CONFLICT (bookmark_id) DO UPDATE SET
    classified_at  = excluded.classified_at,
    applied_labels = excluded.applied_labels,
    llm_model     = excluded.llm_model,
    confidence    = excluded.confidence
`

type UpsertProcessedParams struct {
	BookmarkID    string
	ClassifiedAt  string
	AppliedLabels string
	LlmModel      string
	Confidence    float64
}

func (q *Queries) UpsertProcessed(ctx context.Context, db DBTX, arg UpsertProcessedParams) error {
	_, err := db.ExecContext(ctx, upsertProcessed,
		arg.BookmarkID,
		arg.ClassifiedAt,
		arg.AppliedLabels,
		arg.LlmModel,
		arg.Confidence,
	)
	return err
}
